name: Build on Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"

      - name: Build
        run: go build -v -o .build ./...

      - name: List build output
        run: ls -lah .build/

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: .build/gitea-udpate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
